#don't change this
version: 2

#distance between separate lines
lines_gaps: 0.3

#if hologram packets should be compressed asynchronously
async_batch: false

#how often should be holograms saved to config (in minutes)
save_interval: 5

#grid settings
grid:
  #separator for grid columns
  col_separator: ";"
  #starting sequence for rows that shouldn't be included to the grid
  excluder: "^^"

#MySQL login credentials
mysql:
  host: ""
  port: 3306
  database: ""
  user: ""
  password: ""